# https://www.getambassador.io/docs/emissary/latest/tutorials/quickstart-demo/
#
# Usage
# $ kubectl apply -f examples/emissary-ingress.yaml
# $ export AMBASSADOR_LB_ENDPOINT=$(kubectl -n emissary get svc emissary-ingress -o "go-template={{range .status.loadBalancer.ingress}}{{or .ip .hostname}}{{end}}")
# $ curl -Lk "https://$AMBASSADOR_LB_ENDPOINT/backend/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: quote
    spec:
      containers:
        - name: backend
          image: docker.io/datawire/quote:0.5.0
          ports:
            - name: http
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: quote
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: quote

---
apiVersion: getambassador.io/v3alpha1
kind: Mapping
metadata:
  name: quote-backend
spec:
  hostname: "*"
  prefix: /backend/
  service: quote
